# Generated by Django 4.2.9 on 2024-02-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='source',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='time_inq',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.source'),
        ),
    ]
