# Generated by Django 4.2.9 on 2024-02-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_sp_service'),
        ('dashboard', '0002_alter_customer_employee_alter_customer_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='emirate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.emirate'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.source'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.service'),
        ),
    ]
