# Generated by Django 4.2.9 on 2024-02-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_employee_position'),
        ('dashboard', '0002_remove_customer_source_remove_inquiry_time_inq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateField()),
                ('need', models.TextField()),
                ('price', models.TextField()),
                ('quantity', models.TextField()),
                ('reasons', models.TextField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inquiry')),
                ('quotation_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service')),
            ],
        ),
    ]
