# Generated by Django 4.2.9 on 2024-02-27 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_address_emirate_alter_inquiry_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='services',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.service'),
        ),
    ]
