# Generated by Django 4.2.9 on 2024-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='need',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='reasons',
        ),
        migrations.AddField(
            model_name='quotation',
            name='detail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
