# Generated by Django 4.2.9 on 2024-02-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_inquiry_services_inquiry_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='columns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
