# Generated by Django 4.2.9 on 2024-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_quotationform_service_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quotation',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
