# Generated by Django 4.2.9 on 2024-03-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_booking_booking_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationnotify',
            name='action',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('connecting', 'connecting'), ('send quotation', 'send quotation'), ('pending', 'pending'), ('underpreccess', 'underpreccess')], max_length=50, null=True),
        ),
    ]
