# Generated by Django 4.2.9 on 2024-03-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_permission_name'),
        ('dashboard', '0010_quotationnotify_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuotationNotify',
            new_name='InquiryNotify',
        ),
    ]
