# Generated by Django 4.2.9 on 2024-03-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_quotationnotify_inquirynotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirystatus',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
