# Generated by Django 4.2.9 on 2024-03-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_inquirystatus_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.inquiry'),
        ),
    ]
