# Generated by Django 4.2.9 on 2024-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_isemployeenotified'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
