# Generated by Django 4.2.9 on 2024-03-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_permission_name'),
        ('dashboard', '0019_booking_ref_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isemployeenotified',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='isemployeenotified',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='isemployeenotified',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.service'),
        ),
    ]
