# Generated by Django 4.2.9 on 2024-03-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_isemployeenotified_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isemployeenotified',
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='isemployeenotified',
            name='service',
        ),
    ]
