# Generated by Django 4.2.9 on 2024-03-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_service_reminder_time_alter_inquirynotify_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superprovider',
            name='trn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
