# Generated by Django 4.2.9 on 2024-03-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_superprovider_trn'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_sp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.superprovider'),
        ),
    ]
