# Generated by Django 4.2.9 on 2024-03-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_quotation_quotation_sp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.address'),
        ),
    ]
