# Generated by Django 4.2.9 on 2024-03-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_inquiry_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='sp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.superprovider'),
        ),
    ]
