# Generated by Django 4.2.9 on 2024-03-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_inquiry_sp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superprovider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='superprovider',
            name='phone',
        ),
    ]
