# Generated by Django 4.2.9 on 2024-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_superprovider_search_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='canceling_causes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquirynotify',
            name='action',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('connecting', 'connecting'), ('cancel', 'cancel'), ('send quotation', 'send quotation'), ('pending', 'pending'), ('underpreccess', 'underpreccess'), ('updated', 'updated'), ('reminder', 'reminder')], max_length=50, null=True),
        ),
    ]
