# Generated by Django 4.2.9 on 2024-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_status_canceling_causes_alter_inquirynotify_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='canceling_causes',
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='canceling_causes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
