# Generated by Django 4.2.9 on 2024-03-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_superprovider_email_superprovider_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superprovider',
            name='service',
        ),
        migrations.AddField(
            model_name='superprovider',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.service'),
        ),
    ]
