# Generated by Django 4.2.9 on 2024-03-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_inquirynotify_action_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destination',
        ),
    ]
