# Generated by Django 4.2.9 on 2024-03-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_message_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='destination',
        ),
    ]
