# Generated by Django 4.2.9 on 2024-03-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_message_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='have_reminder',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
