# Generated by Django 4.2.9 on 2024-04-06 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_employee_sp_service_employee_sp'),
        ('dashboard', '0047_messagenotify_isemployeereadmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirystatus',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
    ]
