# Generated by Django 4.2.9 on 2024-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_inquirystatus_employee_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
