# Generated by Django 4.2.9 on 2024-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_service_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='superprovider',
            name='invoice_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='superprovider',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
