# Generated by Django 4.2.9 on 2024-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_superprovider_invoice_count_superprovider_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='invoice_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
