# Generated by Django 4.2.9 on 2024-04-14 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_quotation_invoice_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='invoice_counter',
            new_name='invoice_reference',
        ),
        migrations.RemoveField(
            model_name='superprovider',
            name='invoice_count',
        ),
    ]
