# Generated by Django 4.2.9 on 2024-04-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_rename_invoice_counter_quotation_invoice_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='invoice_reference',
            new_name='invoice_counter',
        ),
    ]
