# Generated by Django 4.2.9 on 2024-04-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_rename_invoice_reference_quotation_invoice_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='invoice_counter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
