# Generated by Django 4.2.9 on 2024-04-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_message_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
