# Generated by Django 4.2.9 on 2024-04-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_email'),
        ('dashboard', '0058_alter_message_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotify',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='of', to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='messagenotify',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me', to='authentication.employee'),
        ),
    ]
