# Generated by Django 4.2.9 on 2024-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_email'),
        ('dashboard', '0059_messagenotify_source_alter_messagenotify_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='handler',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.employee'),
        ),
    ]
