# Generated by Django 4.2.9 on 2024-04-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_email'),
        ('dashboard', '0060_inquiry_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='authentication.employee'),
        ),
    ]
