# Generated by Django 4.2.9 on 2024-05-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_messagenotify_from_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenotify',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.groupmessenger'),
        ),
    ]
