# Generated by Django 4.2.9 on 2024-05-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_messagenotify_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessenger',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
