# Generated by Django 4.2.9 on 2024-05-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_email'),
        ('dashboard', '0065_groupmessenger_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tl', to='authentication.employee'),
        ),
    ]
