# Generated by Django 4.2.9 on 2024-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_inquiry_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='superprovider',
            name='columns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
