# Generated by Django 4.2.9 on 2024-05-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_superprovider_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superprovider',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='superprovider',
            name='search_number',
        ),
    ]
