# Generated by Django 4.2.9 on 2024-05-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_remove_superprovider_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryreminder',
            name='gool',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('inquiry', 'Inquiry')], max_length=10, null=True),
        ),
    ]
