# Generated by Django 4.2.9 on 2024-06-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_inquiryreminder_gool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.CharField(blank=True, choices=[('by call center', 'by call center'), ('work', 'work'), ('visit', 'visit'), ('inspiction', 'inspiction'), ('design', 'design'), ('follow up', 'follow up')], max_length=20, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.inquiry')),
            ],
        ),
    ]
