# Generated by Django 4.2.9 on 2024-06-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.booking'),
        ),
        migrations.AddField(
            model_name='request',
            name='quotation',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.quotation'),
        ),
    ]
