# Generated by Django 4.2.9 on 2024-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_request_booking_request_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
