# Generated by Django 4.2.9 on 2024-07-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_alter_inquirynotify_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirystatus',
            name='preUpdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquirynotify',
            name='action',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('connecting', 'connecting'), ('cancel', 'cancel'), ('send quotation', 'send quotation'), ('send bill', 'send bill'), ('pending', 'pending'), ('underpreccess', 'underpreccess'), ('updated', 'updated'), ('reminder', 'reminder'), ('complain', 'complain'), ('done', 'done'), ('need approve', 'need approve'), ('approvement', 'approvement')], max_length=50, null=True),
        ),
    ]
