# Generated by Django 4.2.9 on 2024-07-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_inquirystatus_preupdate_alter_inquirynotify_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirystatus',
            name='preUpdate',
        ),
    ]
