# Generated by Django 4.2.9 on 2024-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_remove_inquirystatus_preupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirystatus',
            name='cancel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='connectDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='doneDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='pendingDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='sendbDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='sendqDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquirystatus',
            name='underproccessDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
