# Generated by Django 4.2.9 on 2024-07-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_inquirystatus_cancel_inquirystatus_connectdelay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirystatus',
            old_name='cancel',
            new_name='cancelDelay',
        ),
    ]
