# Generated by Django 4.2.9 on 2024-07-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_rename_cancel_inquirystatus_canceldelay'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirystatus',
            name='newDelay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
