# Generated by Django 4.2.9 on 2024-07-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_employee_columns_employee_search_number'),
        ('dashboard', '0079_inquirystatus_newdelay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('number', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('aproved', models.BooleanField(default=False)),
                ('canceling_causes', models.CharField(blank=True, max_length=200, null=True)),
                ('register', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.nationality')),
            ],
        ),
    ]
