# Generated by Django 4.2.9 on 2024-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0080_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
