# Generated by Django 4.2.9 on 2024-07-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0081_points_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='aproved',
            field=models.BooleanField(default=None),
        ),
    ]
