# Generated by Django 4.2.9 on 2024-07-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_alter_points_aproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='aproved',
        ),
        migrations.AddField(
            model_name='points',
            name='approved',
            field=models.CharField(choices=[('T', 'True'), ('F', 'False'), ('N', 'Not yet')], default='N', max_length=1),
        ),
    ]
