# Generated by Django 4.2.9 on 2024-07-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_remove_points_aproved_points_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.inquiry'),
        ),
    ]
