# Generated by Django 4.2.9 on 2024-07-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0085_inquirynotify_point_alter_inquirynotify_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
