# Generated by Django 4.2.9 on 2024-07-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0086_points_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirynotify',
            name='action',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('connecting', 'connecting'), ('cancel', 'cancel'), ('send quotation', 'send quotation'), ('send bill', 'send bill'), ('pending', 'pending'), ('underpreccess', 'underpreccess'), ('updated', 'updated'), ('reminder', 'reminder'), ('complain', 'complain'), ('done', 'done'), ('need approve', 'need approve'), ('approvement', 'approvement'), ('new point', 'new point'), ('one point need rating', 'one point need rating')], max_length=50, null=True),
        ),
    ]
