# Generated by Django 4.2.9 on 2024-08-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0088_service_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
