# Generated by Django 4.2.9 on 2024-08-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_alter_service_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abr', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=5)),
                ('vat', models.FloatField()),
            ],
        ),
    ]
