# Generated by Django 4.2.9 on 2024-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_country_numberprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='imageLinke',
            field=models.TextField(blank=True, default='https://via.placeholder.com/250x150', null=True),
        ),
    ]
