# Generated by Django 4.2.9 on 2024-08-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_country_imagelinke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='vat',
        ),
        migrations.AddField(
            model_name='country',
            name='email',
            field=models.EmailField(default='exemple@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone',
            field=models.CharField(default='00011223344', max_length=15),
            preserve_default=False,
        ),
    ]
