# Generated by Django 4.2.9 on 2024-08-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0094_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceToSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('Marketing_price', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('sp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.superprovider')),
            ],
        ),
    ]
