# Generated by Django 4.2.9 on 2024-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_invoicetosp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetosp',
            name='invoices_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetosp',
            name='marketing_pdf_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetosp',
            name='totalwithoutvat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetosp',
            name='totalwithvat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicetosp',
            name='vat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
