# Generated by Django 4.2.9 on 2024-02-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('agent', 'agent'), ('provider', 'provider')], max_length=16, null=True),
        ),
    ]
