# Generated by Django 4.2.9 on 2024-02-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_customer_employee_alter_customer_language_and_more'),
        ('authentication', '0002_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sp_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.service'),
        ),
    ]
