# Generated by Django 4.2.9 on 2024-03-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_superprovider_email_superprovider_phone_number_and_more'),
        ('authentication', '0006_alter_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sp_service',
        ),
        migrations.AddField(
            model_name='employee',
            name='sp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.superprovider'),
        ),
    ]
