# Generated by Django 4.2.9 on 2024-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='search_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
