# Generated by Django 4.2.9 on 2024-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_employee_columns_employee_search_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
