name: Deploy to Render

on:
  workflow_run:
    workflows: ["Build and Push Docker image to Docker Hub"]
    types:
      - completed

jobs:

  push_to_render:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
