name: Deploy to Render


on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker image to Docker Hub"]
    types:
    - completed

jobs:
  push_to_registry:
    uses: ./.github/workflows/dockerhub.yml
  build:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [push_to_registry]

    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
